"""initial_schema

Revision ID: 155c4b406a77
Revises: 
Create Date: 2026-09-04 19:49:43.592064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155c4b406a77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recovery_opt_out', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_customer_created', 'payments', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_payments_customer_id', 'payments', ['customer_id'], unique=False)
    op.create_table('recovery_attempts',
    sa.Column('recovery_id', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('ml_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('recovery_id')
    )
    op.create_index('ix_recovery_attempts_payment_id', 'recovery_attempts', ['payment_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('recovery_id', sa.String(length=50), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('agent_reason', sa.Text(), nullable=True),
    sa.Column('policy_result', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.ForeignKeyConstraint(['recovery_id'], ['recovery_attempts.recovery_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_logs_payment_id', 'audit_logs', ['payment_id'], unique=False)
    op.create_index('ix_audit_logs_recovery_id', 'audit_logs', ['recovery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_recovery_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_payment_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_recovery_attempts_payment_id', table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index('ix_payments_customer_id', table_name='payments')
    op.drop_index('ix_payments_customer_created', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_table('customers')
    # ### end Alembic commands ###
